https://teamdable.github.io/techblog/PyTorch-Autograd

In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [5]:
# y 는 연산의 결과로 생성된 것이므로 grad_fn 을 갖습니다.
y.grad_fn

In [6]:
z = y * y * 3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [11]:
a = torch.randn(2,2)
a = ((a*3) / (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [14]:
out.backward()
# out.backward(torch.tensor(1.)) 과 동일

In [19]:
# do/dx = do/dz * dz/dy * dy/dx
#       = 1/4 * 6y * 1
#       = 3/2 * y
#       = 3/2 * (x+2)
#       = 3/2 * 3
#       = 9/2

In [15]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [18]:
x = torch.randn(3, requires_grad=True)
y = x * 2
print(x)
print(y)

while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 0.1291, -1.0832,  0.1007], requires_grad=True)
tensor([ 0.2582, -2.1665,  0.2014], grad_fn=<MulBackward0>)
tensor([  132.1867, -1109.2303,   103.1002], grad_fn=<MulBackward0>)


In [20]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [21]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [22]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
